default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: surakshya
  password: 2026
  pool: 5

development:
  <<: *default
  database: enterprise_task_manager_development

test:
  <<: *default
  database: enterprise_task_manager_test

production:
  <<: *default
  database: enterprise_task_manager_production
  username: enterprise_task_manager
  password: <%= ENV['ENTERPRISE_TASK_MANAGER_DATABASE_PASSWORD'] %>
